export const vaccins = [
  {
    Nom: 'BBIBP-CorV',
    Inventeurs: ['Sinopharm'],
    Lieux_de_production: ['Chine'],
    Technologie: 'virus inactivé',
    Quantite: 420,
    Prix_unitaire: '17$',
    Approuve: 'oui',
    Image: 'bbibp-corv.jpg',
  },

  {
    Nom: 'Sputnik V',
    Inventeurs: ['Gamaleya'],
    Lieux_de_production: ['Russie', 'Inde'],
    Technologie: 'adenoviru',
    Quantite: 130,
    Prix_unitaire: '12$',
    Approuve: 'non',
    Image: 'sputnik-v.jpg',
  },
  {
    Nom: 'AZD1222',
    Inventeurs: ['AstraZeneca', 'University of Oxford'],
    Lieux_de_production: ['Royaume Unis', 'Brésil', 'Inde'],
    Technologie: 'adenovirus',
    Quantite: 5028,
    Prix_unitaire: '1.78$',
    Approuve: 'non',
    Image: 'azd1222.jpg',
  },
  {
    Nom: 'Tozinameran',
    Inventeurs: ['BioNTech', 'Pfizer', 'Fosun Pharma'],
    Lieux_de_production: ['Allemagne', 'USA'],
    Technologie: 'ARN messager',
    Quantite: 980,
    Prix_unitaire: '14$ ',
    Approuve: 'oui',
    Image: 'tozinameran.jpg',
  },
  {
    Nom: 'mRNA-1273',
    Inventeurs: ['Moderna', 'NIAID', 'BARDA'],
    Lieux_de_production: ['USA'],
    Technologie: 'ARN messager',
    Quantite: 240,
    Prix_unitaire: '28$',
    Approuve: 'non',
    Image: 'mrna-1273.jpg',
  },
  {
    Nom: 'Ad26.COV2.S',
    Inventeurs: ['Johnson & Johnson', 'BIDMC'],
    Lieux_de_production: ['USA', 'Amérique du Sud', 'Ukraine', 'Afrique du Sud'],
    Technologie: 'adenovirus',
    Quantite: 110,
    Prix_unitaire: '31$',
    Approuve: 'non',
    Image: 'ad26-cov2-s.jpg',
  },
];
